name: finance_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1
  flutter_iconpicker: ^4.0.1
  flutter_iconpicker_plus: ^3.2.3
  
  

  #firebase_core: ^3.6.0
  firebase_core: ^2.32.0

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
    image_path: "icons/app_logo.png"
    android: true
    ios: true
    #background_color: "#FFFFFF"  # Change to any color you prefer

flutter:
  uses-material-design: true

  assets:
    - assets/

