// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3d7q9bazgPQaZvMNgyBLQITs4Okaj-1s',
    appId: '1:672324020810:web:54c49ff51e99019332d4b3',
    messagingSenderId: '672324020810',
    projectId: 'finance-tracker-app-afea4',
    authDomain: 'finance-tracker-app-afea4.firebaseapp.com',
    storageBucket: 'finance-tracker-app-afea4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wCOcH_BEu_OQW4YLaVAYmQYlPJWd1YI',
    appId: '1:672324020810:android:36b596cc342e62ff32d4b3',
    messagingSenderId: '672324020810',
    projectId: 'finance-tracker-app-afea4',
    storageBucket: 'finance-tracker-app-afea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_mHoj5Qj4V8W5vXWRuJDE3ioU9dkhVO8',
    appId: '1:672324020810:ios:b920b1248df5571a32d4b3',
    messagingSenderId: '672324020810',
    projectId: 'finance-tracker-app-afea4',
    storageBucket: 'finance-tracker-app-afea4.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_mHoj5Qj4V8W5vXWRuJDE3ioU9dkhVO8',
    appId: '1:672324020810:ios:b920b1248df5571a32d4b3',
    messagingSenderId: '672324020810',
    projectId: 'finance-tracker-app-afea4',
    storageBucket: 'finance-tracker-app-afea4.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3d7q9bazgPQaZvMNgyBLQITs4Okaj-1s',
    appId: '1:672324020810:web:ac7935c036b9c74432d4b3',
    messagingSenderId: '672324020810',
    projectId: 'finance-tracker-app-afea4',
    authDomain: 'finance-tracker-app-afea4.firebaseapp.com',
    storageBucket: 'finance-tracker-app-afea4.firebasestorage.app',
  );
}
